name: Build Debian Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build debian package
        id: build
        uses: jiro4989/build-deb-action@v4
        with:
          package: onirobuilder
          package_root: onirobuilder_deb
          maintainer: ${{ github.actor }}
          version: ${{ github.ref_name }}
          arch: amd64

      - name: Show resulting deb file
        run: ls ${{ steps.build.outputs.file_name }}

      - name: Upload deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: onirobuilder-deb
          path: ${{ steps.build.outputs.file_name }}
