name: Build Sample App

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: oniro-runner
    container:
      image: francescopham/oniro-builder
    env:
      HOME: /root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and sign app
        run: |
          cd "$GITHUB_WORKSPACE/sample_app"
          onirobuilder sign
          onirobuilder build